[package]
name = "cargotest"
version = "0.1.0"
edition = "2021"


[dependencies]
rand="0.8"
chrono = "0.4"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
colored = "2.0"
termion = "1.5"
log = "0.4"
log4rs = "1.0"